### ISSUE TITLE
Fix `HeroBanner__text` overlaying other elements

### ISSUE THREAD

**Issue by grinkus-adapt** [adaptdk/su-ukraina#245]
### Description

The `HeroBanner__text` is positioned absolutely for some reason and it overlays other elements in the page. It shouldn't.

### Screenshots

![image](https://user-images.githubusercontent.com/12794717/184335675-d49919c4-5d50-497e-a112-d42f1b8dc9c7.png)

### Notes

Maybe `display: flex` would suffice instead of making it `absolute`?

### To reproduce

1. Go to https://suukraina.lt/
1. Resize your viewport to ~640px in width.
1. Check the `HeroBanner__text` position.

### Acceptance criteria

- [ ] `HeroBanner__text` is in the correct place on all layouts and does not overlay other elements.

**Comment by Toxicom** [comment]
![image](https://user-images.githubusercontent.com/69549795/184345662-0c03b559-70a1-4a78-96f2-2c0944ed5f77.png)
Buttons also look dogshit, will see if can fix in same PR
