### ISSUE TITLE
Introduce English instead of Russian langauge in help search

### ISSUE THREAD

**Issue by IamRokas** [adaptdk/su-ukraina#277]
Seeing russian language  annoys the fuck out of UA people. We have to respect that.

Add english language instead of it.

([internal [non-public] forecast link](https://app.forecast.it/project/P-59/workflow/T11677))

**Comment by Clasyc** [comment]
Added support in the Admin UI for en-US language.

https://user-images.githubusercontent.com/17416365/211623917-f69ac94c-8bd4-477c-a598-5169abfdc719.mp4

Front-end adjustments required to support `_en` suffix in Algolia.

**Comment by grinkus-adapt** [comment]
@Clasyc the search is built to expect a value entered for _every_ language. If `en` is missing, then it breaks. If `lt` would be missing, it would also break. To resolve this issue the search needs a refactoring, or we need to make `_en` values required.

CC @IamRokas

**Comment by grinkus-adapt** [comment]
Once `en` values are entered, I think the tweak would be as simple as (and adding translations to the same file):

```diff
diff --git a/src/constants/HelpSearch.js b/src/constants/HelpSearch.js
index 26c001c..c6865a9 100644
--- a/src/constants/HelpSearch.js
+++ b/src/constants/HelpSearch.js
@@ -1,8 +1,9 @@
 export const LANG_LT = `lt`;
 export const LANG_RU = `ru`;
 export const LANG_UK = `uk`;
+export const LANG_EN = `en`;
 
-export const POSSIBLE_SEARCH_LANGS = [LANG_LT, LANG_RU, LANG_UK];
+export const POSSIBLE_SEARCH_LANGS = [LANG_LT, LANG_EN, LANG_RU, LANG_UK];
 
 export const TRANSLATIONS = {
   hit: {
```

CC @Toxicom

**Comment by Clasyc** [comment]
@Toxicom added `_en` values to Algolia.
