### ISSUE TITLE
Extra comma after contact form 

### ISSUE THREAD

**Issue by GediminasMark** [adaptdk/su-ukraina#67]
https://github.com/adaptdk/su-ukraina/blob/5a3df209b8f747700f8ac4758cb2d69fa507e4d0/src/components/Layout/Layout.js#L64

![image](https://user-images.githubusercontent.com/47487261/162817527-97290ec1-96c5-44da-8f32-b9707d75ff64.png)

**Comment by GediminasMark** [comment]
Sry tiesiog akis pastoviai uzkliuna :)

**Comment by grinkus-adapt** [comment]
:smile: dėkui!
